version: "3.7"

services:
  client:
    restart: always
    build:
      context: ./client
    depends_on:
      - server
    ports:
      - "80:80"

  server:
    restart: always
    build:
      context: ./server
    env_file:
      ./server/.env.production
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    restart: always
    image: mongo
    volumes:
      - db_data:/data/db

volumes:
  db_data:
