version: "3.7"

services:
  client:
    build:
      dockerfile: ./docker/dev/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - "./client:/app"
      - "/app/node_modules/"

  server:
    build:
      dockerfile: ./docker/dev/Dockerfile
    ports:
      - "8000:8000"
      - "9229:9229"
    volumes:
      - "./server:/app"
      - "/app/node_modules/"
    env_file:
      ./server/docker/dev/.env
